### ISSUE TITLE
Trash not visible in Lovelace

### ISSUE THREAD

**Issue by pilot1981** [RedFoxy/HA-Separate-Garbage-Collection#2]
Trash not visible in Lovelace: what I can do?

**Comment by RedFoxy** [comment]
Hi!
Did you follow all steps and add a garbage collection item? the trash is not visible if you miss a step like the name in the card, or files to upload or any other step

**Comment by pilot1981** [comment]
I have to modify also card file? Name of entity must be the same used in the card?

**Comment by RedFoxy** [comment]
Sure, all entities must start with "raccolta" (I know... it's an italian word that I forgot to change before to share) like: sensor.raccolta_paper

Than in the card you must change that part (there are more than one:

      ha-card {
        --plastica: hue-rotate(20deg) brightness(1.2);
        --umido   : hue-rotate(00deg) grayscale(50%) brightness(0.7);
        --carta   : hue-rotate(160deg) brightness(0.7);
        --indif   : hue-rotate(0deg) grayscale(100%) brightness(0.7);
        --vetro   : hue-rotate(100deg) brightness(0.7);
        borde-radius: var(--ha-card-border-radius);
        width: 100%;
      }

sensor.raccolta_plastica is --plastica than if you have sensor.raccolta_paper you must be --paper

**Comment by pilot1981** [comment]
Already done…but it don’t solved my problem…

**Comment by RedFoxy** [comment]
Show me your card and garbage collector

**Comment by pilot1981** [comment]
![image](https://user-images.githubusercontent.com/46350465/209983580-b81d44ff-0e01-4edc-97d5-dd1d87532a72.png)

![image](https://user-images.githubusercontent.com/46350465/209983625-2f0773cc-b501-4e26-9eb2-172bd30c5556.png)

![image](https://user-images.githubusercontent.com/46350465/209983719-b33b8269-1327-4f3f-a2b3-d633cdcd6ed8.png)

![image](https://user-images.githubusercontent.com/46350465/209983781-99d7e807-3eb4-43c7-bf7f-6188e8155a86.png)

**Comment by RedFoxy** [comment]
Just I received a ticket about a troubles with the [new Auto Entities](https://github.com/RedFoxy/HA-Separate-Garbage-Collection/issues/3), maybe it's the same issue

**Comment by pilot1981** [comment]
I also found another problem: in the card with trash and buttons, when I setup notification time to 19:05, then when I came back I find 9:05…

**Comment by RedFoxy** [comment]
Just I update the cards and the way of cards get the Garbage Collection items, now you are not forced to name it _sensor.raccolta_, about the notification time, if you want to change it permanently you must edit the garbage_collection.yaml
