### ISSUE TITLE
Nessun Rifiuto Visualizzato

### ISSUE THREAD

**Issue by MattiaFontana997** [RedFoxy/HA-Separate-Garbage-Collection#3]
Dopo aver aggiornato auto-entities non vengono piu visualizzati i rifiuti nella card

**Comment by pilot1981** [comment]
anche a me

**Comment by RedFoxy** [comment]
Grazie per la segnalazione, ora vedo di aggiornare!

**Comment by RedFoxy** [comment]
Ok aggiornato tutte le card, aggiornatele e vedrete che comparirà tutto di nuovo!
Ho anche cambiato il sistema di filtro, adesso tutti gli elementi con _device_class_ **garbage_collection** non importa il nome.
